# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WPZoo Adventure Map
email: coletteisabella@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of stories about the animals who live at The Woodland Park Zoo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: coletteisabella
github_username:  coletteisabella

# Build settings
markdown: kramdown
navigation:
  - text: temperate
    url: temperate/
  - text: Red Panda
    url: redpanda/
  - text: northern
    url: northern/
  - text: Jersey Steer
    url: jerseysteer/
  - text: Crane
    url: crane/
  - text: Flamingos
    url: flamingos/
